### ISSUE TITLE
Local variable might be referenced before assignment

### ISSUE THREAD

**Issue by kripnerl** [kripnerl/pleque#23]
Are you sure that this will not happen? 
https://github.com/kripnerl/pleque/blob/a7d00f9516da2a8ce4faed2b150afbf8749c962c/pleque/core.py#L279

PyCharm gives me: 
Warning:(288, 32) Local variable 'tmp2' might be referenced before assignment

**Comment by MatejTomes** [comment]
ok, this is not an idiot-proof solution. It could happen if no contour was found and that can be achieved by a "skilled" user

**Comment by kripnerl** [comment]
So I suppose empty list or `None` may be returned?
