### ISSUE TITLE
Nine or zero? 

### ISSUE THREAD

**Issue by kripnerl** [kripnerl/pleque#25]
I suppose there should be 9 instead of 0
```python
attrs_pos = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 15, 17]
```
instead of
```python
attrs_pos = [0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 10, 11, 13, 15, 17]
```

https://github.com/kripnerl/pleque/blob/4cb78cc42e2642af51525187134b2ec62f93b87b/pleque/io/readgeqdsk.py#L78

**Comment by MatejTomes** [comment]
yes
