### ISSUE TITLE
The magnetic_axis.R and magnetic_axis.Z does not return R, Z coordinates

### ISSUE THREAD

**Issue by MatejTomes** [kripnerl/pleque#29]
https://github.com/kripnerl/pleque/blob/a1f203fb08c77f39e26c872d0fe4c30f72047850/pleque/core.py#L506

**Comment by MatejTomes** [comment]
def magnetic_axis(self):
        return self.coordinates(R = self._mg_axis[0], Z=self._mg_axis[1])

this works

**Comment by kripnerl** [comment]
resolve by #32
