### ISSUE TITLE
Equilibrium.psi_n function not returning correct values

### ISSUE THREAD

**Issue by MatejTomes** [kripnerl/pleque#9]
Equilibrium._psi_lcfs wrongly identified in Equilibrium.__find_extremes__

I discovered this issue by using Equilibrium.psi_n function which returns wrong values.

**Comment by kripnerl** [comment]
`Equilibrium.__findextremes__()` done more robust. Waiting for function `self.in_first_wall` for better recognition of `lcfs`.

**Comment by MatejTomes** [comment]
in_first_wall function inside the utils/surfaces.py

**Comment by kripnerl** [comment]
Should be resolved with #10
